visibility.exe H:\intrinsic_image_work_record\data_NEW Aloe view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Art view1 view5E2
visibility.exe H:\intrinsic_image_work_record\data_NEW Baby1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Baby2 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Baby3 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Books view1 view5E2
visibility.exe H:\intrinsic_image_work_record\data_NEW Bowling1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Bowling2 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Cloth1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Cloth2 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Cloth3 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Cloth4 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Dolls view1 view5E2
visibility.exe H:\intrinsic_image_work_record\data_NEW Flowerpots view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Lampshade1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Lampshade2 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Laundry view1 view5E2
visibility.exe H:\intrinsic_image_work_record\data_NEW Midd1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Midd2 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Moebius view1 view5E2
visibility.exe H:\intrinsic_image_work_record\data_NEW Monopoly view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Plastic view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Reindeer view1 view5E2
visibility.exe H:\intrinsic_image_work_record\data_NEW Rocks1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Rocks2 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Wood1 view1 view5E1
visibility.exe H:\intrinsic_image_work_record\data_NEW Wood2 view1 view5E1